return {
    ascii = {
        cpu = "Cpu",
        gpu = "Gpu",
        mem = "Mem",
        eth = "Eth",
        wifi = "Wln",
        net = "Net",
        net_disabled = "Net-x-",
        disc = "Df",
        clock = "",
        battery = "Bat?",
        battery_charging = "Bat+",
        battery_discharging = "Bat-",
        AC = "Psu",
        snd = "Snd",
        snd_mute = "Snd-x-",
        -- temperature = "\\u00B0 C",
        temperature = "C",
    },
    awesome = {
        cpu = "Cpu",
        gpu = "Gpu",
        mem = "Mem",
        eth = "Eth",
        wifi = "Wlan",
        net = "Net",
        net_disabled = "Net-x-",
        disc = "Df",
        clock = "T-",
        battery = "Bat",
        AC = "Pow",
        snd = "Snd",
        snd_mute = "Snd-x-",
        temperature = "Th",
    }
}
